version: '3'
################################################################################
### Networks
################################################################################
networks:
  laravel:



################################################################################
### Service
################################################################################

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    links:
      - client
   
    